---
- name: Restart Docker Service
  hosts: all
  become: yes
  tasks:
    - name: Stop Docker
      service:
        name: docker
        state: stopped

    - name: Start Docker
      shell: sudo docker-compose up
