---
- name: Restart Docker Service
  hosts: all
  become: yes
  tasks:
    - name: Stop Docker
      service:
        name: docker
        state: stopped
        
    - name: Wait for 5 seconds
      pause:
        seconds: 5
        
    - name: Start Docker
      shell: sudo docker-compose up
